name: env
channels:
- conda-forge
- defaults
dependencies:
- numpy
- scipy
- xarray
- dask
- netcdf4
- jupyter
- jupyterlab
- matplotlib
- cmocean
- pandas
- cartopy
- tqdm                                                    # for generating progressbars for timed processes
- statsmodels
- ipython
- xgcm
- basemap
- pip    
- opencv                                                  # useful for contour fitting
- xmitgcm
- cmaps
- pip:
  - git+https://github.com/retostauffer/python-colorspace # hcl scientific colormaps
  - gsw                                                   # gibbs sea-water TEOS10 function
  - PyCO2SYS                                              # python wrapper for the CO2SYS matlab functions
  - geopy                                                 # useful lat lon to distance approximations
  - git+https://github.com/nsidc/polarstereo-lonlat-convert-py.git # for sea ice field projections (annoying...)
  - seabird                                               # used to parse seabird CTD observations
